from . import account_account
from . import account_move
from . import account_payment
from . import journal_entry
from . import journal
from . import product_template
from . import res_partner
from . import voucher
from . import analytic_account
from . import tax
from . import account_group
from . import operating_unit
from . import qm_production
from . import purchase
from . import purchase_quotation
from . import attendance
from . import hr_employee
from . import stock_warehouse
from . import stock_receipt_bill
from . import stock_request
from . import account_multicompany
from . import hr_salary
from . import sale
from . import invoice_bill
from . import quarry_management
from . import closing_stock
from . import stock_transfer
from . import stock_return
