from . import account_api
from . import account_move_api
from . import account_payment_api
from . import journal_entry_api
from . import journal_api
from . import voucher_api
from . import product_api
from . import partner_api
from . import analytic_account_api
from . import tax_api
from . import account_group_api
from . import operating_unit_api
from . import qm_production_api
from . import purchase_api
from . import purchase_quotation_api
from . import attendance_api
from . import hr_employee_api
from . import stock_warehouse_api
from . import stock_receipt_bill_api
from . import stock_request_api
from . import account_multicompany_api
from . import hr_salary_api
from . import sale_api
from . import invoice_bill_api
from . import quarry_management_api
from . import closing_stock_api
from . import stock_transfer_api
from . import stock_return_api

